### ISSUE TITLE
Hello!

### ISSUE THREAD

**Issue by sekim67** [jcarreira/disag-firebox#1]
Dear Sir!

We implement a rdma client at running linux kernel. We found your project. Thanks for your job.

I know that a IB Client for kernel module must call ib_register_client. I could found it from the codes.

The client_module_init() functions never return, But instead endless loop. 

If your code is running as successful, you must modify it. I hope so your modification ASAP. 

Thanks.

**Comment by huzaifakam** [comment]
ib_poll_cq(cq, 1, &wc){
    if(wc.status == IB_WC_SUCCESS) 
    else
        printk("Failure: %d\n", wc.status);
}
This prints Failure 12. Can you identify the issue?

**Comment by jcarreira** [comment]
Thanks for the comment. Can you create a pull request or suggest code changes?
