### ISSUE TITLE
Saw your old question

### ISSUE THREAD

**Issue by baik33** [jcarreira/disag-firebox#4]
Hello Joao,
 
 I saw your question https://stackoverflow.com/questions/44190665/rdma-between-gpu-and-remote-host. Did you get the answer? I got the normal RDMA mechanics to work with queue pairs, now I'm trying to send data directly to a memory allocated by cudaMalloc so the data would get directly to GPU. Not sure how to do it .

**Comment by jcarreira** [comment]
I ended up not pursuing this work. Unfortunately, can't help you much regarding this.
